=== amaoxia/iSwap-CloudCentre/iSwap-CloudCentre/src/config/configuration.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema 由 XMLSpy v2006 U 创建 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="category">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="entry" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="chName" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MongoDBServer配置文件"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="enName" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MongoDB"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="prop" maxOccurs="unbounded"/>
				<xs:element ref="dictionary"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dictionary">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="category" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="entry">
		<xs:complexType>
			<xs:attribute name="code" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="192.168.100.235"/>
						<xs:enumeration value="192.168.100.236"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:short">
						<xs:enumeration value="30000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="def" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="prop">
		<xs:complexType>
			<xs:attribute name="value" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="../lib"/>
						<xs:enumeration value="../webapps/iswaphome/deptLogo"/>
						<xs:enumeration value="../webapps/iswaphome/finallyReport"/>
						<xs:enumeration value="../webapps/iswaphome/sysReport"/>
						<xs:enumeration value="../webapps/iswaphome/temp"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="key" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="deptLogo"/>
						<xs:enumeration value="finallyReport"/>
						<xs:enumeration value="jarpath"/>
						<xs:enumeration value="sysReport"/>
						<xs:enumeration value="temp"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== amaoxia/iSwap-CloudCentre/iSwap-CloudCentre/webapp/WEB-INF/classes/config/config.xml
<?xml version="1.0" encoding="gbk" standalone="yes"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configuration.xsd">
	<prop value="../lib" key="jarpath"/>
	<!-- 临时目录 -->
	<prop value="../webapps/iswaphome/temp" key="temp"/>
	<!--绩效考核 系统报告 -->
	<prop value="../webapps/iswaphome/sysReport" key="sysReport"/>
	<!-- 绩效考核 人工上传报告 -->
	<prop value="../webapps/iswaphome/finallyReport" key="finallyReport"/>
	<!--  部门LOGO -->
	<prop value="../webapps/iswaphome/deptLogo" key="deptLogo"/>
	<!-- 指标模板 -->
	<prop value="../webapps/iswaphome/itemTemplate" key="itemTemplate"/>
<!-- 	 上传文档数据目录 -->
	<prop value="../webapps/iswaphome/itemDocument" key="itemDocument"/>
	<!--  交换文档成功目录 -->
	<prop value="../webapps/iswaphome/exchangeSuccDocument" key="exchangeSuccDocument"/>
	<!--  文档共享区目录 -->
	<prop value="../webapps/iswaphome/shareDocument" key="shareDocument"/>
	<!--  单点登陆WS服务地址 -->
	<prop value="http://192.168.100.39:8080/fusionids/service/IFusionIDSWebService" key="webService_url"/>
	
	<prop value="../lib" key="jarpath"/>
	<!-- FPT输出目录 -->
	<prop value="/err" key="ftpPutpath"/>
	<dictionary>
		<category chName="MongoDBServer配置文件" enName="MongoDB">
			<entry code="127.0.0.1"  name="27017"   def="" />
		</category>
	</dictionary>  
	</configuration>
